---
title: "Final_Project"
author: "Jared"
date: '2023-06-14'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(esquisse)
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
master<-read_csv("/Users/jaredhayes/Downloads/archive/Master.csv")
pitching<-read_csv("/Users/jaredhayes/Downloads/archive/Pitching.csv")
batting<-read_csv("/Users/jaredhayes/Downloads/archive/Batting.csv")
HOF<-read_csv("/Users/jaredhayes/Downloads/archive/HallOfFame.csv")
pitching<-pitching%>%
  mutate(IP=IPouts/3)%>%
  group_by(playerID)%>%
  summarise(wins=sum(W),total_IP=sum(IPouts),avg_ERA=mean(ERA))
batting<-batting%>%
  mutate(batting_average=H/AB)%>%
  group_by(playerID)%>%
  summarise(hits=sum(H),HRS=sum(HR),average_average=mean(batting_average))
HOF<-HOF%>%
  filter(inducted=="Y"&category=="Player")%>%
  select(playerID,inducted)
master<-master%>%
  select(playerID,nameFirst,nameLast)
 
master_pitching<-left_join(master,pitching)
master_batting<-left_join(master,batting)
master_HOF<-left_join(master,HOF)
master_HOF$inducted <- ifelse(is.na(master_HOF$inducted), "N", master_HOF$inducted)
master_pitching<-na.omit(master_pitching)
master_batting<-na.omit(master_batting)
HOF_batting<-left_join(master_batting,master_HOF)
HOF_pitching<-left_join(master_pitching,master_HOF)
HOF_batting$initial_last <- sub("^([A-Za-z]).*\\s(.*)$", "\\1 \\2", paste(HOF_batting$nameFirst, HOF_batting$nameLast))
HOF_pitching$initial_last<-sub("^([A-Za-z]).*\\s(.*)$", "\\1 \\2", paste(HOF_pitching$nameFirst,HOF_pitching$nameLast))
```


```{r}
 


```
```{r}
ggplot(HOF_batting) +
  aes(
    x = average_average,
    y = hits,
    colour = inducted,
    size = HRS
  ) +
  geom_point(shape = "circle") +
  scale_color_hue(direction = 1) +
  theme_minimal()
ggplot(HOF_pitching) +
  aes(x = avg_ERA, y = wins, colour = total_IP) +
  geom_point(shape = "circle", size = 1.5) +
  scale_color_gradient() +
  theme_minimal() +
  facet_wrap(vars(inducted))+
  xlim(0,10)
ggplot(HOF_pitching) +
  aes(x = wins, y = total_IP) +
  geom_point(shape = "circle", size = 1.5, colour = "#112446") +
  theme_minimal() +
  facet_wrap(vars(inducted))+geom_smooth(method = "lm", se = FALSE, color = "blue") 
```
```{r}
new_data<-read_csv("/Users/jaredhayes/Downloads/mlbbat10.csv")
new_data$initial_last<-new_data$name
combined_data<-left_join(new_data,HOF_batting)
combined_data<-combined_data%>%
  filter(game>30)
#esquisse::esquisser(data=combined_data)
ggplot(combined_data) +
  aes(x = slg, y = HRS, size = obp) +
  geom_point(shape = "circle", colour = "#112446") +
  theme_minimal()+
  xlim(0,1)
```

 
